version: '3.8'

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/traefik/traefik.yml:/traefik.yml:ro
      - ./data/traefik/acme.json:/acme.json
    environment:
      - CF_API_EMAIL=${CLOUDFLARE_EMAIL}
      # نکته مهم: CF_API_KEY یا CF_DNS_API_TOKEN باید به عنوان Secret در داکر تعریف شود
      # برای سادگی در این مثال، آن را به عنوان متغیر محیطی در نظر می‌گیریم
      # - CF_DNS_API_TOKEN=your_cloudflare_dns_api_token
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik-dashboard.rule=Host(`traefik.${DOMAIN_NAME}`)"
      - "traefik.http.routers.traefik-dashboard.service=api@internal"
      - "traefik.http.routers.traefik-dashboard.tls=true"
      - "traefik.http.routers.traefik-dashboard.tls.certresolver=cloudflare"
      - "traefik.http.routers.traefik-dashboard.middlewares=auth"
      - "traefik.http.middlewares.auth.basicauth.users=${TRAEFIK_AUTH}"

  wordpress:
    image: wordpress:6.4-php8.2-fpm-alpine
    container_name: wordpress
    restart: unless-stopped
    volumes:
      - ./data/wordpress:/var/www/html
    environment:
      - WORDPRESS_DB_HOST=mariadb:3306
      - WORDPRESS_DB_USER=${DB_USER}
      - WORDPRESS_DB_PASSWORD=${DB_PASSWORD}
      - WORDPRESS_DB_NAME=${DB_NAME}
    depends_on:
      - mariadb
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress.rule=Host(`${DOMAIN_NAME}`)"
      - "traefik.http.routers.wordpress.entrypoints=websecure"
      - "traefik.http.routers.wordpress.tls=true"
      - "traefik.http.routers.wordpress.tls.certresolver=cloudflare"
      - "traefik.http.services.wordpress.loadbalancer.server.port=9000"

  mariadb:
    image: mariadb:10.11
    container_name: mariadb
    restart: unless-stopped
    volumes:
      - ./data/mariadb:/var/lib/mysql
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${DB_NAME}
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASSWORD}
    command: '--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci'

  redis:
    image: redis:7.2-alpine
    container_name: redis
    restart: unless-stopped
    command: redis-server --save 60 1 --loglevel warning

volumes:
  traefik_data:
  wordpress_data:
  db_data: